name:                eventdb
version:             0.1.0.0
github:              "ahri/eventdb"
license:             BSD3
author:              "Adam Piper"
maintainer:          "adam@ahri.net"
copyright:           "2019"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            A simple database to store a stream of events (facts) and retrieve them by index
# category:            prototype

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ahri/eventdb#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- unix-bytestring
- unix
- directory
- filepath
- safe-exceptions
- stm

library:
  source-dirs: src

executables:

  eventdb-util:
    main:                Main.hs
    source-dirs:         app-eventdb-util
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - eventdb
    - text
    - async

  bank-acct-demo:
    main:                Main.hs
    source-dirs:         app-bank-acct-demo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - eventdb
    - async
    - random
    - directory

  client-demo:
    main:                Main.hs
    source-dirs:         app-client-demo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - eventdb
    - directory

  mem-profile-file-write:
    main:                Main.hs
    source-dirs:         app-mem-profile-file-write
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - eventdb
    - directory

  mem-profile-file-read:
    main:                Main.hs
    source-dirs:         app-mem-profile-file-read
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - eventdb
    - directory

  mem-profile-stream-read:
    main:                Main.hs
    source-dirs:         app-mem-profile-stream-read
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - eventdb
    - directory

# tests:
#   eventdb-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - eventdb
